language: python
python:
- 2.7
env:
  global:
  - secure: jSXWLkfX/plvfFrR/aEJZHBcINgeYIYAbUVzLdn40Oe9vosWo+6WhEx6UFEqU5ZPlFr5KhHxMXktpFFjJZe+t8FhlzxbAJBfHOkQE4fVJYaO0EkahEd6crHjp7dJyLACu1i7+XqyrGkbupBh5APXf85uhBk4PNmrZM/y1AEoZcQ=
  - secure: FDJYhJMpwKi9sWC01ZgAoz0xoRubJvhycLlQvzVeadXNaTi/zrLXkfEzn1+4iGhl++evQe/rS75jvk5BYOV18nWrJSm8b/F91WEkFnZLvudV+90XEmk7G1x4Vu1kSP8YRlF3SZ3jILaMlpte9SI/quiBbA2w9uu87gTuiHE8Mdk=
  matrix:
  - DJANGO_VERSION=1.5.5
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install -U django==$DJANGO_VERSION
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- firefox &
- sleep 3
script:
- coverage run --source=escenario,generator manage.py test generator
after_success:
- coveralls
