language: python
python:
- 3.4
env:
  global:
  - secure: jSXWLkfX/plvfFrR/aEJZHBcINgeYIYAbUVzLdn40Oe9vosWo+6WhEx6UFEqU5ZPlFr5KhHxMXktpFFjJZe+t8FhlzxbAJBfHOkQE4fVJYaO0EkahEd6crHjp7dJyLACu1i7+XqyrGkbupBh5APXf85uhBk4PNmrZM/y1AEoZcQ=
  - secure: QieaVS+0WkrTq9M7ZpKn8BIZ42qTcDkjwKpIaLmP7yfvPfZHAa3l9wHY1bkjnRFXIJ3Ac7Vn5ddvslg2TUmmaK8HurXkZVamJ4xp4rjOWPsiWr0M4JndDnOulREMu6Lf8uXIf3ncIw4+CbapJH2odEO5AwSYEhG49+Y4go97sMg=
install:
- pip install -r requirements.txt
- pip install coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- firefox &
- sleep 3
script:
- coverage run --source=escenario,generator manage.py test generator
after_success:
- coveralls
