language: python
python:
- 2.7
env:
  global:
  - secure: jSXWLkfX/plvfFrR/aEJZHBcINgeYIYAbUVzLdn40Oe9vosWo+6WhEx6UFEqU5ZPlFr5KhHxMXktpFFjJZe+t8FhlzxbAJBfHOkQE4fVJYaO0EkahEd6crHjp7dJyLACu1i7+XqyrGkbupBh5APXf85uhBk4PNmrZM/y1AEoZcQ=
  - secure: QlgZn75yC8b5/h1kr/IKT7DYnBWajWV+xAV9reFHEJn6qX60i7EGDtVY1J7COmPIESkDw8iLbKMsVyxjVApXA79yqUbXHlhBbYuD58S2/l5E9FvHGzlApntbrh0YTXkx31Bz8v9ewINxUSiAPOGCeoDuj7+JQxFkNrhv8CwYUU8=
  matrix:
  - DJANGO_VERSION=1.5.5
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install -U django==$DJANGO_VERSION
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- firefox &
- sleep 3
script:
- coverage run --source=escenario,generator manage.py test generator
after_success:
- coveralls
